# Generated by Django 5.1.3 on 2024-11-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
